### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by YasogaN** [keifufu/WebNowPlaying#27]
The Mozilla Addon store link under [Installing](https://github.com/keifufu/WebNowPlaying#installing) in the README points to a broken link (https://addons.mozilla.org/en-US/firefox/addon/webnowplaying). It should be corrected to https://addons.mozilla.org/en-US/firefox/addon/webnowplaying-redux

**Comment by keifufu** [comment]
That's true, I recently updated the repo but have not yet updated the items on the webstores, the link will be correct once they are updated.
