### ISSUE TITLE
Title shows " ft." (Standardize Featuring enabled) even though there is nothing playing or there is playing but does not have Feat. (or similar) on YouTube

### ISSUE THREAD

**Issue by jbcarreon123** [keifufu/WebNowPlaying#31]
## Steps of Reproduction
1. Enable "Standardize Featuring" on settings
2. Select one of each
  2.1. Open YouTube but don't click on a video - stay on homepage or non-video pages
  2.2. Open a video on YouTube
3. See the issue on the title
## Expected Behavior
There should be nothing or the normal video title
## Current Behavior
There is a " ft." showing in the title field even though there is no Featuring thing on the normal title
## Screenshots
![image](https://github.com/keifufu/WebNowPlaying/assets/86447165/9dd76224-376c-4881-b638-3136fd7199e3)
![image](https://github.com/keifufu/WebNowPlaying/assets/86447165/2fe69a7a-6c85-4adf-81e3-4a9f82a5520e)
![image](https://github.com/keifufu/WebNowPlaying/assets/86447165/3b9ea4d5-7f04-417c-a9a9-05e87354109d)

**Comment by keifufu** [comment]
I can't replicate this, do you have other sanitization options enabled?
Could you provide a link for a video where this is happening?

**Comment by jbcarreon123** [comment]
> I can't replicate this, do you have other sanitization options enabled?
When it happens, I have all sanitization options enabled.
![image](https://github.com/keifufu/WebNowPlaying/assets/86447165/96181f1f-4b68-4f26-b2a7-5d5d4c01aefa)

> Could you provide a link for a video where this is happening?
Also, it happens on any video, even on the youtube homepage.
![image](https://github.com/keifufu/WebNowPlaying/assets/86447165/c173b515-2fc0-4041-8fca-9f866faba41b)

**Comment by keifufu** [comment]
fixed in ac2159d6be3cceb2cfb55c72468085416db2a00a
