### ISSUE TITLE
Possible issue with Spotify Web Player

### ISSUE THREAD

**Issue by convalise** [keifufu/WebNowPlaying#36]
Hello.
I'm using the extension (v3.0.1) together with your Rainmeter plugin (v2.0.7).
On Spotify Web Player (https://open.spotify.com) it stopped reporting the Progress, Position and Duration.
Other calls work as expected.

Also, SetPosition seems to have stopped working as well.

To test it you can used the SASMusicPlayer (https://github.com/DerianMelvin/SASMusicPlayer) but you have to update the Rainmeter plugin that comes with it.

Testing on YouTube:
![image](https://github.com/keifufu/WebNowPlaying/assets/12805305/9fb97de0-72c3-448c-950c-7288ec2a39ab)

Testing on Spotify:
![image](https://github.com/keifufu/WebNowPlaying/assets/12805305/f2eeba0c-3f2c-4bd8-bf65-31ea7ec97384)

The SASMusicPlayer doesn't let you seek, but I have a personal skin that uses SetPosition and it worked on YouTube but not on Spotify Web Player.

EDIT: forgot to mention, I'm using the Chrome extension on Chrome version 125.0.6422.142.

**Comment by keifufu** [comment]
Will test Spotify web player tomorrow on Firefox.

**Comment by keifufu** [comment]
Spotify changed their class names again, will be fixed in the next update.

**Comment by keifufu** [comment]
Spotify has done some other changes fucking with our ability to set the position and volume. I cannot figure out how to resolve this right now.
Feel free to look into this yourself (setting the position and volume in percent via the console), but I can't figure it out for now.
