### ISSUE TITLE
Chrome unsuccessfully attempts to connect to rainmeter

### ISSUE THREAD

**Issue by BruninDoMine** [keifufu/WebNowPlaying#39]
It's a recurring issue, I still haven't been able to connect them

![image](https://github.com/keifufu/WebNowPlaying/assets/149852331/00f5bfe4-1f88-4920-b3af-ebcb340a6d9d)

Attempted solutions:
1-) Allowing Rainmeter through firewall
2-) Allowing the extension thorugh Ublock Origin
3-) Restarting the adapter

Can anyone help me with this?

**Comment by keifufu** [comment]
Make sure you have a skin loaded that uses webnowplaying, otherwise there is nothing to connect to. 

Otherwise, try turning off the checkbox next to rainmeter in your image and turn it on again after a minute or two.

**Comment by keifufu** [comment]
Mondtholomew does, the original mond does not.
https://mondtholomew.rainmeter.skin/

**Comment by BruninDoMine** [comment]
Okay, now webnowplaying connected, but for some reason the rainmeter media player doesn't work

**Comment by keifufu** [comment]
make sure you actually use mondtholomews player

**Comment by BruninDoMine** [comment]
I'm using this player

**Comment by keifufu** [comment]
please join the rainmeter discord and get help there.
